# Need these for a more recent CMake on Linux
sudo: required
dist: bionic

os:
  - linux
  - osx

language: cpp

before_script:
  - cd watched
  - mkdir build
  - cd build
  - cmake ..

script:
  - cmake --build .

after_script:
  - cmake --build . --target watched_test

# This section installs the necessary dependencies.
addons:
  apt:
    packages:
    - g++
    - clang
    update: true
  homebrew:
    packages:
    - ccache
    - gcc@7.5
    - llvm@4
    update: true
