# Need these for a more recent CMake on Linux
sudo: required
dist: bionic

os:
  - linux
  - osx

language: cpp

before_script:
  - cd watched
  - mkdir build
  - cd build
  - cmake ..

script:
  - cmake --build .

after_script:
  - cmake --build . --target watched_test
